CREATE TABLE `comune_istat` (
	`CD_COMUNE` VARCHAR(5) NOT NULL,
	`DENOMINAZIONE_COMUNE` VARCHAR(100) NOT NULL,
	`ID_CODICE_CATASTO` VARCHAR(5) NOT NULL,
	`CODICE_ISTAT_COMUNE` VARCHAR(6) NOT NULL,
	`SIGLA_PROVINCIA` VARCHAR(3) NOT NULL,
	PRIMARY KEY (`CD_COMUNE`),
	INDEX `FK_PROVINCE_idx` (`SIGLA_PROVINCIA`)
)
COMMENT='TABELLA CONTENTE I COMUNI ITALIANI'
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;
