CREATE TABLE `provincia` (
  `SIGLA_PROVINCIA` varchar(2) NOT NULL,
  `CODICE_ISTAT_REGIONE` varchar(2) NOT NULL,
  `CODICE_ISTAT_PROVINCIA` varchar(3) NOT NULL,
  `PROVINCIA` varchar(50) NOT NULL,
  PRIMARY KEY (`SIGLA_PROVINCIA`),
  KEY `FK_REGIONI_idx` (`CODICE_ISTAT_REGIONE`),
  CONSTRAINT `FK_REGIONI` FOREIGN KEY (`CODICE_ISTAT_REGIONE`) REFERENCES `regione` (`CODICE_ISTAT_REGIONE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='TABELLA CONTENENTE LE PROVINCE ITALIANE'$$



INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('AG','19','084','Agrigento');                                                                                                
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('AL','01','006','Alessandria');                                                                                              
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('AN','11','042','Ancona');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('AO','02','007','Aosta');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('AP','11','044','Ascoli Piceno');                                                                                            
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('AQ','13','066','Aquila');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('AR','09','051','Arezzo');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('AT','01','005','Asti');                                                                                                     
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('AV','15','064','Avellino');                                                                                                 
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('BA','16','072','Bari');                                                                                                     
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('BG','03','016','Bergamo');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('BI','01','096','Biella');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('BL','05','025','Belluno');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('BN','15','062','Benevento');                                                                                                
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('BO','08','037','Bologna');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('BR','16','074','Brindisi');                                                                                                 
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('BS','03','017','Brescia');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('BZ','04','021','Bolzano');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('CA','20','092','Cagliari');                                                                                                 
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('CB','14','070','Campobasso');                                                                                               
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('CE','15','061','Caserta');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('CH','13','069','Chieti');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('CL','19','085','Caltanissetta');                                                                                            
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('CN','01','004','Cuneo');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('CO','03','013','Como');                                                                                                     
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('CR','03','019','Cremona');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('CS','18','078','Cosenza');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('CT','19','087','Catania');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('CZ','18','079','Catanzaro');                                                                                                
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('EN','19','086','Enna');                                                                                                     
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('FE','08','038','Ferrara');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('FG','16','071','Foggia');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('FI','09','048','Firenze');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('FO','08','040','Forli');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('FR','12','060','Frosinone');                                                                                                
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('GE','07','010','Genova');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('GO','06','031','Gorizia');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('GR','09','053','Grosseto');                                                                                                 
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('IM','07','008','Imperia');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('IS','14','094','Isernia');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('KR','18','101','Crotone');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('LC','03','097','Lecco');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('LE','16','075','Lecce');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('LI','09','049','Livorno');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('LO','03','098','Lodi');                                                                                                     
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('LT','12','059','Latina');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('LU','09','046','Lucca');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('MC','11','043','Macerata');                                                                                                 
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('ME','19','083','Messina');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('MI','03','015','Milano');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('MN','03','020','Mantova');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('MO','08','036','Modena');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('MS','09','045','Massa Carrara');                                                                                            
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('MT','17','077','Matera');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('NA','15','063','Napoli');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('NO','01','003','Novara');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('NU','20','091','Nuoro');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('OR','20','095','Oristano');                                                                                                 
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PA','19','082','Palermo');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PC','08','033','Piacenza');                                                                                                 
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PD','05','028','Padova');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PE','13','068','Pescara');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PG','10','054','Perugia');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PI','09','050','Pisa');                                                                                                     
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PN','06','093','Pordenone');                                                                                                
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PO','09','100','Prato');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PR','08','034','Parma');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PS','11','041','Pesaro');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PT','09','047','Pistoia');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PV','03','018','Pavia');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PZ','17','076','Potenza');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('RA','08','039','Ravenna');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('RC','18','080','Reggio Calabria');                                                                                          
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('RE','08','035','Reggio Emilia');                                                                                            
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('RG','19','088','Ragusa');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('RI','12','057','Rieti');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('RM','12','058','Roma');                                                                                                     
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('RN','08','099','Rimini');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('RO','05','029','Rovigo');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('SA','15','065','Salerno');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('SI','09','052','Siena');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('SO','03','014','Sondrio');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('SP','07','011','La Spezia');                                                                                                
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('SR','19','089','Siracusa');                                                                                                 
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('SS','20','090','Sassari');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('SV','07','009','Savona');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('TA','16','073','Taranto');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('TE','13','067','Teramo');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('TN','04','022','Trento');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('TO','01','001','Torino');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('TP','19','081','Trapani');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('TR','10','055','Terni');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('TS','06','032','Trieste');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('TV','05','026','Treviso');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('UD','06','030','Udine');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('VA','03','012','Varese');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('VB','01','103','Verbano-Cusio-Ossola');                                                                                     
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('VC','01','002','Vercelli');                                                                                                 
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('VE','05','027','Venezia');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('VI','05','024','Vicenza');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('VR','05','023','Verona');                                                                                                   
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('VT','12','056','Viterbo');                                                                                                  
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('VV','18','102','Vibo Valentia');                                                                                            
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('SM','00','000','San Marino');                                                                                               
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('MB','03','108','Monza Brianza');                                                                                            
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('FM','11','150','Fermo');                                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('BT','16','110','Barletta-Andria-Trani');                                                                                    
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('CI','20','107','Carbonia-Iglesias');                                                                                        
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('FC','08','040','Forli-Cesena');                                                                                             
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('OG','20','105','Ogliastra');                                                                                                
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('OT','20','104','Olbia-Tempio');                                                                                             
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('PU','11','041','Pesaro e Urbino');                                                                                          
INSERT INTO GESTCONFDB.provincia (sigla_provincia,codice_istat_regione,codice_istat_provincia,provincia) VALUES ('VS','20','106','Medio Campidano');                                                                                          



