package com.gestioneconferenzews.DAO.model;

import java.util.Date;

public class CodaFatturazione {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column coda_fatturazione.cd_coda_fatturazione
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private Integer cdCodaFatturazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column coda_fatturazione.cd_persona
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private Integer cdPersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column coda_fatturazione.cd_pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private Integer cdPagamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column coda_fatturazione.data_elaborazione
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private Date dataElaborazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column coda_fatturazione.cd_coda_fatturazione
	 * @return  the value of coda_fatturazione.cd_coda_fatturazione
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public Integer getCdCodaFatturazione() {
		return cdCodaFatturazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column coda_fatturazione.cd_coda_fatturazione
	 * @param cdCodaFatturazione  the value for coda_fatturazione.cd_coda_fatturazione
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setCdCodaFatturazione(Integer cdCodaFatturazione) {
		this.cdCodaFatturazione = cdCodaFatturazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column coda_fatturazione.cd_persona
	 * @return  the value of coda_fatturazione.cd_persona
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public Integer getCdPersona() {
		return cdPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column coda_fatturazione.cd_persona
	 * @param cdPersona  the value for coda_fatturazione.cd_persona
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setCdPersona(Integer cdPersona) {
		this.cdPersona = cdPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column coda_fatturazione.cd_pagamento
	 * @return  the value of coda_fatturazione.cd_pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public Integer getCdPagamento() {
		return cdPagamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column coda_fatturazione.cd_pagamento
	 * @param cdPagamento  the value for coda_fatturazione.cd_pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setCdPagamento(Integer cdPagamento) {
		this.cdPagamento = cdPagamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column coda_fatturazione.data_elaborazione
	 * @return  the value of coda_fatturazione.data_elaborazione
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public Date getDataElaborazione() {
		return dataElaborazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column coda_fatturazione.data_elaborazione
	 * @param dataElaborazione  the value for coda_fatturazione.data_elaborazione
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setDataElaborazione(Date dataElaborazione) {
		this.dataElaborazione = dataElaborazione;
	}
}