package com.gestioneconferenzews.DAO.model;

public class ComitatoPersona {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comitato_persona.cd_comitato_persona
	 * @mbggenerated  Wed Apr 02 22:57:42 CEST 2014
	 */
	private Integer cdComitatoPersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comitato_persona.cd_persona
	 * @mbggenerated  Wed Apr 02 22:57:42 CEST 2014
	 */
	private Integer cdPersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comitato_persona.cd_comitato
	 * @mbggenerated  Wed Apr 02 22:57:42 CEST 2014
	 */
	private Integer cdComitato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comitato_persona.chair
	 * @mbggenerated  Wed Apr 02 22:57:42 CEST 2014
	 */
	private Integer chair;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comitato_persona.cd_comitato_persona
	 * @return  the value of comitato_persona.cd_comitato_persona
	 * @mbggenerated  Wed Apr 02 22:57:42 CEST 2014
	 */
	public Integer getCdComitatoPersona() {
		return cdComitatoPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comitato_persona.cd_comitato_persona
	 * @param cdComitatoPersona  the value for comitato_persona.cd_comitato_persona
	 * @mbggenerated  Wed Apr 02 22:57:42 CEST 2014
	 */
	public void setCdComitatoPersona(Integer cdComitatoPersona) {
		this.cdComitatoPersona = cdComitatoPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comitato_persona.cd_persona
	 * @return  the value of comitato_persona.cd_persona
	 * @mbggenerated  Wed Apr 02 22:57:42 CEST 2014
	 */
	public Integer getCdPersona() {
		return cdPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comitato_persona.cd_persona
	 * @param cdPersona  the value for comitato_persona.cd_persona
	 * @mbggenerated  Wed Apr 02 22:57:42 CEST 2014
	 */
	public void setCdPersona(Integer cdPersona) {
		this.cdPersona = cdPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comitato_persona.cd_comitato
	 * @return  the value of comitato_persona.cd_comitato
	 * @mbggenerated  Wed Apr 02 22:57:42 CEST 2014
	 */
	public Integer getCdComitato() {
		return cdComitato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comitato_persona.cd_comitato
	 * @param cdComitato  the value for comitato_persona.cd_comitato
	 * @mbggenerated  Wed Apr 02 22:57:42 CEST 2014
	 */
	public void setCdComitato(Integer cdComitato) {
		this.cdComitato = cdComitato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comitato_persona.chair
	 * @return  the value of comitato_persona.chair
	 * @mbggenerated  Wed Apr 02 22:57:42 CEST 2014
	 */
	public Integer getChair() {
		return chair;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comitato_persona.chair
	 * @param chair  the value for comitato_persona.chair
	 * @mbggenerated  Wed Apr 02 22:57:42 CEST 2014
	 */
	public void setChair(Integer chair) {
		this.chair = chair;
	}
}