package com.gestioneconferenzews.DAO.model;

public class ComuneIstat {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comune_istat.CD_COMUNE
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	private String cdComune;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comune_istat.DENOMINAZIONE_COMUNE
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	private String denominazioneComune;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comune_istat.ID_CODICE_CATASTO
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	private String idCodiceCatasto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comune_istat.CODICE_ISTAT_COMUNE
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	private String codiceIstatComune;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comune_istat.SIGLA_PROVINCIA
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	private String siglaProvincia;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comune_istat.CD_COMUNE
	 * @return  the value of comune_istat.CD_COMUNE
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	public String getCdComune() {
		return cdComune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comune_istat.CD_COMUNE
	 * @param cdComune  the value for comune_istat.CD_COMUNE
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	public void setCdComune(String cdComune) {
		this.cdComune = cdComune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comune_istat.DENOMINAZIONE_COMUNE
	 * @return  the value of comune_istat.DENOMINAZIONE_COMUNE
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	public String getDenominazioneComune() {
		return denominazioneComune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comune_istat.DENOMINAZIONE_COMUNE
	 * @param denominazioneComune  the value for comune_istat.DENOMINAZIONE_COMUNE
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	public void setDenominazioneComune(String denominazioneComune) {
		this.denominazioneComune = denominazioneComune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comune_istat.ID_CODICE_CATASTO
	 * @return  the value of comune_istat.ID_CODICE_CATASTO
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	public String getIdCodiceCatasto() {
		return idCodiceCatasto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comune_istat.ID_CODICE_CATASTO
	 * @param idCodiceCatasto  the value for comune_istat.ID_CODICE_CATASTO
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	public void setIdCodiceCatasto(String idCodiceCatasto) {
		this.idCodiceCatasto = idCodiceCatasto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comune_istat.CODICE_ISTAT_COMUNE
	 * @return  the value of comune_istat.CODICE_ISTAT_COMUNE
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	public String getCodiceIstatComune() {
		return codiceIstatComune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comune_istat.CODICE_ISTAT_COMUNE
	 * @param codiceIstatComune  the value for comune_istat.CODICE_ISTAT_COMUNE
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	public void setCodiceIstatComune(String codiceIstatComune) {
		this.codiceIstatComune = codiceIstatComune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comune_istat.SIGLA_PROVINCIA
	 * @return  the value of comune_istat.SIGLA_PROVINCIA
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	public String getSiglaProvincia() {
		return siglaProvincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comune_istat.SIGLA_PROVINCIA
	 * @param siglaProvincia  the value for comune_istat.SIGLA_PROVINCIA
	 * @mbggenerated  Tue Apr 15 21:14:27 CEST 2014
	 */
	public void setSiglaProvincia(String siglaProvincia) {
		this.siglaProvincia = siglaProvincia;
	}
}