package com.gestioneconferenzews.DAO.model;

import java.util.Date;

public class Contatto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contatto.cd_contatto
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	private Integer cdContatto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contatto.tipo
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	private String tipo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contatto.contatto
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	private String contatto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contatto.data_annullamento
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	private Date dataAnnullamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contatto.cd_persona
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	private Integer cdPersona;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contatto.cd_contatto
	 * @return  the value of contatto.cd_contatto
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	public Integer getCdContatto() {
		return cdContatto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contatto.cd_contatto
	 * @param cdContatto  the value for contatto.cd_contatto
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	public void setCdContatto(Integer cdContatto) {
		this.cdContatto = cdContatto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contatto.tipo
	 * @return  the value of contatto.tipo
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	public String getTipo() {
		return tipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contatto.tipo
	 * @param tipo  the value for contatto.tipo
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contatto.contatto
	 * @return  the value of contatto.contatto
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	public String getContatto() {
		return contatto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contatto.contatto
	 * @param contatto  the value for contatto.contatto
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	public void setContatto(String contatto) {
		this.contatto = contatto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contatto.data_annullamento
	 * @return  the value of contatto.data_annullamento
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	public Date getDataAnnullamento() {
		return dataAnnullamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contatto.data_annullamento
	 * @param dataAnnullamento  the value for contatto.data_annullamento
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	public void setDataAnnullamento(Date dataAnnullamento) {
		this.dataAnnullamento = dataAnnullamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contatto.cd_persona
	 * @return  the value of contatto.cd_persona
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	public Integer getCdPersona() {
		return cdPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contatto.cd_persona
	 * @param cdPersona  the value for contatto.cd_persona
	 * @mbggenerated  Tue Mar 18 22:25:59 CET 2014
	 */
	public void setCdPersona(Integer cdPersona) {
		this.cdPersona = cdPersona;
	}
}