package com.gestioneconferenzews.DAO.model;

public class ElencoStatistiche {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column elenco_statistiche.cd_elenco_statistiche
	 * @mbggenerated  Thu Apr 24 10:04:48 CEST 2014
	 */
	private Integer cdElencoStatistiche;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column elenco_statistiche.query
	 * @mbggenerated  Thu Apr 24 10:04:48 CEST 2014
	 */
	private String query;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column elenco_statistiche.nome
	 * @mbggenerated  Thu Apr 24 10:04:48 CEST 2014
	 */
	private String nome;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column elenco_statistiche.cd_elenco_statistiche
	 * @return  the value of elenco_statistiche.cd_elenco_statistiche
	 * @mbggenerated  Thu Apr 24 10:04:48 CEST 2014
	 */
	public Integer getCdElencoStatistiche() {
		return cdElencoStatistiche;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column elenco_statistiche.cd_elenco_statistiche
	 * @param cdElencoStatistiche  the value for elenco_statistiche.cd_elenco_statistiche
	 * @mbggenerated  Thu Apr 24 10:04:48 CEST 2014
	 */
	public void setCdElencoStatistiche(Integer cdElencoStatistiche) {
		this.cdElencoStatistiche = cdElencoStatistiche;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column elenco_statistiche.query
	 * @return  the value of elenco_statistiche.query
	 * @mbggenerated  Thu Apr 24 10:04:48 CEST 2014
	 */
	public String getQuery() {
		return query;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column elenco_statistiche.query
	 * @param query  the value for elenco_statistiche.query
	 * @mbggenerated  Thu Apr 24 10:04:48 CEST 2014
	 */
	public void setQuery(String query) {
		this.query = query;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column elenco_statistiche.nome
	 * @return  the value of elenco_statistiche.nome
	 * @mbggenerated  Thu Apr 24 10:04:48 CEST 2014
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column elenco_statistiche.nome
	 * @param nome  the value for elenco_statistiche.nome
	 * @mbggenerated  Thu Apr 24 10:04:48 CEST 2014
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}
}