package com.gestioneconferenzews.DAO.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PagamentoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public PagamentoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCdPagamentoIsNull() {
			addCriterion("cd_pagamento is null");
			return (Criteria) this;
		}

		public Criteria andCdPagamentoIsNotNull() {
			addCriterion("cd_pagamento is not null");
			return (Criteria) this;
		}

		public Criteria andCdPagamentoEqualTo(Integer value) {
			addCriterion("cd_pagamento =", value, "cdPagamento");
			return (Criteria) this;
		}

		public Criteria andCdPagamentoNotEqualTo(Integer value) {
			addCriterion("cd_pagamento <>", value, "cdPagamento");
			return (Criteria) this;
		}

		public Criteria andCdPagamentoGreaterThan(Integer value) {
			addCriterion("cd_pagamento >", value, "cdPagamento");
			return (Criteria) this;
		}

		public Criteria andCdPagamentoGreaterThanOrEqualTo(Integer value) {
			addCriterion("cd_pagamento >=", value, "cdPagamento");
			return (Criteria) this;
		}

		public Criteria andCdPagamentoLessThan(Integer value) {
			addCriterion("cd_pagamento <", value, "cdPagamento");
			return (Criteria) this;
		}

		public Criteria andCdPagamentoLessThanOrEqualTo(Integer value) {
			addCriterion("cd_pagamento <=", value, "cdPagamento");
			return (Criteria) this;
		}

		public Criteria andCdPagamentoIn(List<Integer> values) {
			addCriterion("cd_pagamento in", values, "cdPagamento");
			return (Criteria) this;
		}

		public Criteria andCdPagamentoNotIn(List<Integer> values) {
			addCriterion("cd_pagamento not in", values, "cdPagamento");
			return (Criteria) this;
		}

		public Criteria andCdPagamentoBetween(Integer value1, Integer value2) {
			addCriterion("cd_pagamento between", value1, value2, "cdPagamento");
			return (Criteria) this;
		}

		public Criteria andCdPagamentoNotBetween(Integer value1, Integer value2) {
			addCriterion("cd_pagamento not between", value1, value2,
					"cdPagamento");
			return (Criteria) this;
		}

		public Criteria andDataPagamentoIsNull() {
			addCriterion("data_pagamento is null");
			return (Criteria) this;
		}

		public Criteria andDataPagamentoIsNotNull() {
			addCriterion("data_pagamento is not null");
			return (Criteria) this;
		}

		public Criteria andDataPagamentoEqualTo(Date value) {
			addCriterion("data_pagamento =", value, "dataPagamento");
			return (Criteria) this;
		}

		public Criteria andDataPagamentoNotEqualTo(Date value) {
			addCriterion("data_pagamento <>", value, "dataPagamento");
			return (Criteria) this;
		}

		public Criteria andDataPagamentoGreaterThan(Date value) {
			addCriterion("data_pagamento >", value, "dataPagamento");
			return (Criteria) this;
		}

		public Criteria andDataPagamentoGreaterThanOrEqualTo(Date value) {
			addCriterion("data_pagamento >=", value, "dataPagamento");
			return (Criteria) this;
		}

		public Criteria andDataPagamentoLessThan(Date value) {
			addCriterion("data_pagamento <", value, "dataPagamento");
			return (Criteria) this;
		}

		public Criteria andDataPagamentoLessThanOrEqualTo(Date value) {
			addCriterion("data_pagamento <=", value, "dataPagamento");
			return (Criteria) this;
		}

		public Criteria andDataPagamentoIn(List<Date> values) {
			addCriterion("data_pagamento in", values, "dataPagamento");
			return (Criteria) this;
		}

		public Criteria andDataPagamentoNotIn(List<Date> values) {
			addCriterion("data_pagamento not in", values, "dataPagamento");
			return (Criteria) this;
		}

		public Criteria andDataPagamentoBetween(Date value1, Date value2) {
			addCriterion("data_pagamento between", value1, value2,
					"dataPagamento");
			return (Criteria) this;
		}

		public Criteria andDataPagamentoNotBetween(Date value1, Date value2) {
			addCriterion("data_pagamento not between", value1, value2,
					"dataPagamento");
			return (Criteria) this;
		}

		public Criteria andCdMetodoPagamentoIsNull() {
			addCriterion("cd_metodo_pagamento is null");
			return (Criteria) this;
		}

		public Criteria andCdMetodoPagamentoIsNotNull() {
			addCriterion("cd_metodo_pagamento is not null");
			return (Criteria) this;
		}

		public Criteria andCdMetodoPagamentoEqualTo(Integer value) {
			addCriterion("cd_metodo_pagamento =", value, "cdMetodoPagamento");
			return (Criteria) this;
		}

		public Criteria andCdMetodoPagamentoNotEqualTo(Integer value) {
			addCriterion("cd_metodo_pagamento <>", value, "cdMetodoPagamento");
			return (Criteria) this;
		}

		public Criteria andCdMetodoPagamentoGreaterThan(Integer value) {
			addCriterion("cd_metodo_pagamento >", value, "cdMetodoPagamento");
			return (Criteria) this;
		}

		public Criteria andCdMetodoPagamentoGreaterThanOrEqualTo(Integer value) {
			addCriterion("cd_metodo_pagamento >=", value, "cdMetodoPagamento");
			return (Criteria) this;
		}

		public Criteria andCdMetodoPagamentoLessThan(Integer value) {
			addCriterion("cd_metodo_pagamento <", value, "cdMetodoPagamento");
			return (Criteria) this;
		}

		public Criteria andCdMetodoPagamentoLessThanOrEqualTo(Integer value) {
			addCriterion("cd_metodo_pagamento <=", value, "cdMetodoPagamento");
			return (Criteria) this;
		}

		public Criteria andCdMetodoPagamentoIn(List<Integer> values) {
			addCriterion("cd_metodo_pagamento in", values, "cdMetodoPagamento");
			return (Criteria) this;
		}

		public Criteria andCdMetodoPagamentoNotIn(List<Integer> values) {
			addCriterion("cd_metodo_pagamento not in", values,
					"cdMetodoPagamento");
			return (Criteria) this;
		}

		public Criteria andCdMetodoPagamentoBetween(Integer value1,
				Integer value2) {
			addCriterion("cd_metodo_pagamento between", value1, value2,
					"cdMetodoPagamento");
			return (Criteria) this;
		}

		public Criteria andCdMetodoPagamentoNotBetween(Integer value1,
				Integer value2) {
			addCriterion("cd_metodo_pagamento not between", value1, value2,
					"cdMetodoPagamento");
			return (Criteria) this;
		}

		public Criteria andCdPersonaIsNull() {
			addCriterion("cd_persona is null");
			return (Criteria) this;
		}

		public Criteria andCdPersonaIsNotNull() {
			addCriterion("cd_persona is not null");
			return (Criteria) this;
		}

		public Criteria andCdPersonaEqualTo(Integer value) {
			addCriterion("cd_persona =", value, "cdPersona");
			return (Criteria) this;
		}

		public Criteria andCdPersonaNotEqualTo(Integer value) {
			addCriterion("cd_persona <>", value, "cdPersona");
			return (Criteria) this;
		}

		public Criteria andCdPersonaGreaterThan(Integer value) {
			addCriterion("cd_persona >", value, "cdPersona");
			return (Criteria) this;
		}

		public Criteria andCdPersonaGreaterThanOrEqualTo(Integer value) {
			addCriterion("cd_persona >=", value, "cdPersona");
			return (Criteria) this;
		}

		public Criteria andCdPersonaLessThan(Integer value) {
			addCriterion("cd_persona <", value, "cdPersona");
			return (Criteria) this;
		}

		public Criteria andCdPersonaLessThanOrEqualTo(Integer value) {
			addCriterion("cd_persona <=", value, "cdPersona");
			return (Criteria) this;
		}

		public Criteria andCdPersonaIn(List<Integer> values) {
			addCriterion("cd_persona in", values, "cdPersona");
			return (Criteria) this;
		}

		public Criteria andCdPersonaNotIn(List<Integer> values) {
			addCriterion("cd_persona not in", values, "cdPersona");
			return (Criteria) this;
		}

		public Criteria andCdPersonaBetween(Integer value1, Integer value2) {
			addCriterion("cd_persona between", value1, value2, "cdPersona");
			return (Criteria) this;
		}

		public Criteria andCdPersonaNotBetween(Integer value1, Integer value2) {
			addCriterion("cd_persona not between", value1, value2, "cdPersona");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaIsNull() {
			addCriterion("cd_conferenza is null");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaIsNotNull() {
			addCriterion("cd_conferenza is not null");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaEqualTo(Integer value) {
			addCriterion("cd_conferenza =", value, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaNotEqualTo(Integer value) {
			addCriterion("cd_conferenza <>", value, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaGreaterThan(Integer value) {
			addCriterion("cd_conferenza >", value, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaGreaterThanOrEqualTo(Integer value) {
			addCriterion("cd_conferenza >=", value, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaLessThan(Integer value) {
			addCriterion("cd_conferenza <", value, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaLessThanOrEqualTo(Integer value) {
			addCriterion("cd_conferenza <=", value, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaIn(List<Integer> values) {
			addCriterion("cd_conferenza in", values, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaNotIn(List<Integer> values) {
			addCriterion("cd_conferenza not in", values, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaBetween(Integer value1, Integer value2) {
			addCriterion("cd_conferenza between", value1, value2,
					"cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaNotBetween(Integer value1, Integer value2) {
			addCriterion("cd_conferenza not between", value1, value2,
					"cdConferenza");
			return (Criteria) this;
		}

		public Criteria andTotaleEuroIsNull() {
			addCriterion("totale_euro is null");
			return (Criteria) this;
		}

		public Criteria andTotaleEuroIsNotNull() {
			addCriterion("totale_euro is not null");
			return (Criteria) this;
		}

		public Criteria andTotaleEuroEqualTo(Integer value) {
			addCriterion("totale_euro =", value, "totaleEuro");
			return (Criteria) this;
		}

		public Criteria andTotaleEuroNotEqualTo(Integer value) {
			addCriterion("totale_euro <>", value, "totaleEuro");
			return (Criteria) this;
		}

		public Criteria andTotaleEuroGreaterThan(Integer value) {
			addCriterion("totale_euro >", value, "totaleEuro");
			return (Criteria) this;
		}

		public Criteria andTotaleEuroGreaterThanOrEqualTo(Integer value) {
			addCriterion("totale_euro >=", value, "totaleEuro");
			return (Criteria) this;
		}

		public Criteria andTotaleEuroLessThan(Integer value) {
			addCriterion("totale_euro <", value, "totaleEuro");
			return (Criteria) this;
		}

		public Criteria andTotaleEuroLessThanOrEqualTo(Integer value) {
			addCriterion("totale_euro <=", value, "totaleEuro");
			return (Criteria) this;
		}

		public Criteria andTotaleEuroIn(List<Integer> values) {
			addCriterion("totale_euro in", values, "totaleEuro");
			return (Criteria) this;
		}

		public Criteria andTotaleEuroNotIn(List<Integer> values) {
			addCriterion("totale_euro not in", values, "totaleEuro");
			return (Criteria) this;
		}

		public Criteria andTotaleEuroBetween(Integer value1, Integer value2) {
			addCriterion("totale_euro between", value1, value2, "totaleEuro");
			return (Criteria) this;
		}

		public Criteria andTotaleEuroNotBetween(Integer value1, Integer value2) {
			addCriterion("totale_euro not between", value1, value2,
					"totaleEuro");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoIsNull() {
			addCriterion("tipo_movimento is null");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoIsNotNull() {
			addCriterion("tipo_movimento is not null");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoEqualTo(String value) {
			addCriterion("tipo_movimento =", value, "tipoMovimento");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoNotEqualTo(String value) {
			addCriterion("tipo_movimento <>", value, "tipoMovimento");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoGreaterThan(String value) {
			addCriterion("tipo_movimento >", value, "tipoMovimento");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoGreaterThanOrEqualTo(String value) {
			addCriterion("tipo_movimento >=", value, "tipoMovimento");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoLessThan(String value) {
			addCriterion("tipo_movimento <", value, "tipoMovimento");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoLessThanOrEqualTo(String value) {
			addCriterion("tipo_movimento <=", value, "tipoMovimento");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoLike(String value) {
			addCriterion("tipo_movimento like", value, "tipoMovimento");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoNotLike(String value) {
			addCriterion("tipo_movimento not like", value, "tipoMovimento");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoIn(List<String> values) {
			addCriterion("tipo_movimento in", values, "tipoMovimento");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoNotIn(List<String> values) {
			addCriterion("tipo_movimento not in", values, "tipoMovimento");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoBetween(String value1, String value2) {
			addCriterion("tipo_movimento between", value1, value2,
					"tipoMovimento");
			return (Criteria) this;
		}

		public Criteria andTipoMovimentoNotBetween(String value1, String value2) {
			addCriterion("tipo_movimento not between", value1, value2,
					"tipoMovimento");
			return (Criteria) this;
		}

		public Criteria andTipologiaIsNull() {
			addCriterion("tipologia is null");
			return (Criteria) this;
		}

		public Criteria andTipologiaIsNotNull() {
			addCriterion("tipologia is not null");
			return (Criteria) this;
		}

		public Criteria andTipologiaEqualTo(Integer value) {
			addCriterion("tipologia =", value, "tipologia");
			return (Criteria) this;
		}

		public Criteria andTipologiaNotEqualTo(Integer value) {
			addCriterion("tipologia <>", value, "tipologia");
			return (Criteria) this;
		}

		public Criteria andTipologiaGreaterThan(Integer value) {
			addCriterion("tipologia >", value, "tipologia");
			return (Criteria) this;
		}

		public Criteria andTipologiaGreaterThanOrEqualTo(Integer value) {
			addCriterion("tipologia >=", value, "tipologia");
			return (Criteria) this;
		}

		public Criteria andTipologiaLessThan(Integer value) {
			addCriterion("tipologia <", value, "tipologia");
			return (Criteria) this;
		}

		public Criteria andTipologiaLessThanOrEqualTo(Integer value) {
			addCriterion("tipologia <=", value, "tipologia");
			return (Criteria) this;
		}

		public Criteria andTipologiaIn(List<Integer> values) {
			addCriterion("tipologia in", values, "tipologia");
			return (Criteria) this;
		}

		public Criteria andTipologiaNotIn(List<Integer> values) {
			addCriterion("tipologia not in", values, "tipologia");
			return (Criteria) this;
		}

		public Criteria andTipologiaBetween(Integer value1, Integer value2) {
			addCriterion("tipologia between", value1, value2, "tipologia");
			return (Criteria) this;
		}

		public Criteria andTipologiaNotBetween(Integer value1, Integer value2) {
			addCriterion("tipologia not between", value1, value2, "tipologia");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pagamento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pagamento
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 02 22:57:42 CEST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}