package com.gestioneconferenzews.DAO.model;

import java.util.Date;

public class Persona {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.cd_persona
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private Integer cdPersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.nome
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private String nome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.cognome
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private String cognome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.data_nascita
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private Date dataNascita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.codice_fiscale
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private String codiceFiscale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.partita_iva
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private String partitaIva;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.cd_comune_istat_nascita
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private String cdComuneIstatNascita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.data_creazione
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.affiliazione
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private String affiliazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private Integer tipoPartecipante;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.cd_persona
	 * @return  the value of persona.cd_persona
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public Integer getCdPersona() {
		return cdPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.cd_persona
	 * @param cdPersona  the value for persona.cd_persona
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setCdPersona(Integer cdPersona) {
		this.cdPersona = cdPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.nome
	 * @return  the value of persona.nome
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.nome
	 * @param nome  the value for persona.nome
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.cognome
	 * @return  the value of persona.cognome
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public String getCognome() {
		return cognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.cognome
	 * @param cognome  the value for persona.cognome
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.data_nascita
	 * @return  the value of persona.data_nascita
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public Date getDataNascita() {
		return dataNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.data_nascita
	 * @param dataNascita  the value for persona.data_nascita
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setDataNascita(Date dataNascita) {
		this.dataNascita = dataNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.codice_fiscale
	 * @return  the value of persona.codice_fiscale
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public String getCodiceFiscale() {
		return codiceFiscale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.codice_fiscale
	 * @param codiceFiscale  the value for persona.codice_fiscale
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setCodiceFiscale(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.partita_iva
	 * @return  the value of persona.partita_iva
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public String getPartitaIva() {
		return partitaIva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.partita_iva
	 * @param partitaIva  the value for persona.partita_iva
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setPartitaIva(String partitaIva) {
		this.partitaIva = partitaIva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.cd_comune_istat_nascita
	 * @return  the value of persona.cd_comune_istat_nascita
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public String getCdComuneIstatNascita() {
		return cdComuneIstatNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.cd_comune_istat_nascita
	 * @param cdComuneIstatNascita  the value for persona.cd_comune_istat_nascita
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setCdComuneIstatNascita(String cdComuneIstatNascita) {
		this.cdComuneIstatNascita = cdComuneIstatNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.data_creazione
	 * @return  the value of persona.data_creazione
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.data_creazione
	 * @param dataCreazione  the value for persona.data_creazione
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.affiliazione
	 * @return  the value of persona.affiliazione
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public String getAffiliazione() {
		return affiliazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.affiliazione
	 * @param affiliazione  the value for persona.affiliazione
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setAffiliazione(String affiliazione) {
		this.affiliazione = affiliazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.tipo_partecipante
	 * @return  the value of persona.tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public Integer getTipoPartecipante() {
		return tipoPartecipante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.tipo_partecipante
	 * @param tipoPartecipante  the value for persona.tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setTipoPartecipante(Integer tipoPartecipante) {
		this.tipoPartecipante = tipoPartecipante;
	}
}