package com.gestioneconferenzews.DAO.model;

public class Provincia {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column provincia.SIGLA_PROVINCIA
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	private String siglaProvincia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column provincia.CODICE_ISTAT_REGIONE
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	private String codiceIstatRegione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column provincia.CODICE_ISTAT_PROVINCIA
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	private String codiceIstatProvincia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column provincia.PROVINCIA
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	private String provincia;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column provincia.SIGLA_PROVINCIA
	 * @return  the value of provincia.SIGLA_PROVINCIA
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	public String getSiglaProvincia() {
		return siglaProvincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column provincia.SIGLA_PROVINCIA
	 * @param siglaProvincia  the value for provincia.SIGLA_PROVINCIA
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	public void setSiglaProvincia(String siglaProvincia) {
		this.siglaProvincia = siglaProvincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column provincia.CODICE_ISTAT_REGIONE
	 * @return  the value of provincia.CODICE_ISTAT_REGIONE
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	public String getCodiceIstatRegione() {
		return codiceIstatRegione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column provincia.CODICE_ISTAT_REGIONE
	 * @param codiceIstatRegione  the value for provincia.CODICE_ISTAT_REGIONE
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	public void setCodiceIstatRegione(String codiceIstatRegione) {
		this.codiceIstatRegione = codiceIstatRegione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column provincia.CODICE_ISTAT_PROVINCIA
	 * @return  the value of provincia.CODICE_ISTAT_PROVINCIA
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	public String getCodiceIstatProvincia() {
		return codiceIstatProvincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column provincia.CODICE_ISTAT_PROVINCIA
	 * @param codiceIstatProvincia  the value for provincia.CODICE_ISTAT_PROVINCIA
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	public void setCodiceIstatProvincia(String codiceIstatProvincia) {
		this.codiceIstatProvincia = codiceIstatProvincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column provincia.PROVINCIA
	 * @return  the value of provincia.PROVINCIA
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	public String getProvincia() {
		return provincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column provincia.PROVINCIA
	 * @param provincia  the value for provincia.PROVINCIA
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}
}