package com.gestioneconferenzews.DAO.model;

public class Regione {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regione.CODICE_ISTAT_REGIONE
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	private String codiceIstatRegione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regione.REGIONE
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	private String regione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regione.CODICE_ISTAT_REGIONE
	 * @return  the value of regione.CODICE_ISTAT_REGIONE
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	public String getCodiceIstatRegione() {
		return codiceIstatRegione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regione.CODICE_ISTAT_REGIONE
	 * @param codiceIstatRegione  the value for regione.CODICE_ISTAT_REGIONE
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	public void setCodiceIstatRegione(String codiceIstatRegione) {
		this.codiceIstatRegione = codiceIstatRegione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regione.REGIONE
	 * @return  the value of regione.REGIONE
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	public String getRegione() {
		return regione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regione.REGIONE
	 * @param regione  the value for regione.REGIONE
	 * @mbggenerated  Sat Apr 05 10:37:54 CEST 2014
	 */
	public void setRegione(String regione) {
		this.regione = regione;
	}
}