package com.gestioneconferenzews.DAO.model;

public class ReportAutore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_autore.cd_report_autore
     *
     * @mbggenerated Thu Apr 24 10:04:48 CEST 2014
     */
    private Integer cdReportAutore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_autore.cd_report
     *
     * @mbggenerated Thu Apr 24 10:04:48 CEST 2014
     */
    private Integer cdReport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_autore.cd_persona
     *
     * @mbggenerated Thu Apr 24 10:04:48 CEST 2014
     */
    private Integer cdPersona;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_autore.cd_report_autore
     *
     * @return the value of report_autore.cd_report_autore
     *
     * @mbggenerated Thu Apr 24 10:04:48 CEST 2014
     */
    public Integer getCdReportAutore() {
        return cdReportAutore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_autore.cd_report_autore
     *
     * @param cdReportAutore the value for report_autore.cd_report_autore
     *
     * @mbggenerated Thu Apr 24 10:04:48 CEST 2014
     */
    public void setCdReportAutore(Integer cdReportAutore) {
        this.cdReportAutore = cdReportAutore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_autore.cd_report
     *
     * @return the value of report_autore.cd_report
     *
     * @mbggenerated Thu Apr 24 10:04:48 CEST 2014
     */
    public Integer getCdReport() {
        return cdReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_autore.cd_report
     *
     * @param cdReport the value for report_autore.cd_report
     *
     * @mbggenerated Thu Apr 24 10:04:48 CEST 2014
     */
    public void setCdReport(Integer cdReport) {
        this.cdReport = cdReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_autore.cd_persona
     *
     * @return the value of report_autore.cd_persona
     *
     * @mbggenerated Thu Apr 24 10:04:48 CEST 2014
     */
    public Integer getCdPersona() {
        return cdPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_autore.cd_persona
     *
     * @param cdPersona the value for report_autore.cd_persona
     *
     * @mbggenerated Thu Apr 24 10:04:48 CEST 2014
     */
    public void setCdPersona(Integer cdPersona) {
        this.cdPersona = cdPersona;
    }
}