package com.gestioneconferenzews.DAO.model;

public class Report {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column report.cd_report
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private Integer cdReport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column report.cd_persona
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private Integer cdPersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column report.nomefile
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private String nomefile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column report.cd_conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private Integer cdConferenza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column report.cd_tipo_report
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private Integer cdTipoReport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column report.accettato
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private Integer accettato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column report.valutazione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private Integer valutazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column report.cd_report
	 * @return  the value of report.cd_report
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Integer getCdReport() {
		return cdReport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column report.cd_report
	 * @param cdReport  the value for report.cd_report
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setCdReport(Integer cdReport) {
		this.cdReport = cdReport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column report.cd_persona
	 * @return  the value of report.cd_persona
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Integer getCdPersona() {
		return cdPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column report.cd_persona
	 * @param cdPersona  the value for report.cd_persona
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setCdPersona(Integer cdPersona) {
		this.cdPersona = cdPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column report.nomefile
	 * @return  the value of report.nomefile
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public String getNomefile() {
		return nomefile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column report.nomefile
	 * @param nomefile  the value for report.nomefile
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setNomefile(String nomefile) {
		this.nomefile = nomefile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column report.cd_conferenza
	 * @return  the value of report.cd_conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Integer getCdConferenza() {
		return cdConferenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column report.cd_conferenza
	 * @param cdConferenza  the value for report.cd_conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setCdConferenza(Integer cdConferenza) {
		this.cdConferenza = cdConferenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column report.cd_tipo_report
	 * @return  the value of report.cd_tipo_report
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Integer getCdTipoReport() {
		return cdTipoReport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column report.cd_tipo_report
	 * @param cdTipoReport  the value for report.cd_tipo_report
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setCdTipoReport(Integer cdTipoReport) {
		this.cdTipoReport = cdTipoReport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column report.accettato
	 * @return  the value of report.accettato
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Integer getAccettato() {
		return accettato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column report.accettato
	 * @param accettato  the value for report.accettato
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setAccettato(Integer accettato) {
		this.accettato = accettato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column report.valutazione
	 * @return  the value of report.valutazione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Integer getValutazione() {
		return valutazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column report.valutazione
	 * @param valutazione  the value for report.valutazione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setValutazione(Integer valutazione) {
		this.valutazione = valutazione;
	}
}