package com.gestioneconferenzews.DAO.model;

import java.util.Date;

public class Sessione {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sessione.cd_sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private Integer cdSessione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sessione.cd_conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private Integer cdConferenza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sessione.cd_report
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private Integer cdReport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sessione.ora_inizio
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private Date oraInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sessione.ora_fine
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private Date oraFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sessione.tipo_sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private String tipoSessione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sessione.cd_persona_chair
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	private Integer cdPersonaChair;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sessione.cd_sessione
	 * @return  the value of sessione.cd_sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Integer getCdSessione() {
		return cdSessione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sessione.cd_sessione
	 * @param cdSessione  the value for sessione.cd_sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setCdSessione(Integer cdSessione) {
		this.cdSessione = cdSessione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sessione.cd_conferenza
	 * @return  the value of sessione.cd_conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Integer getCdConferenza() {
		return cdConferenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sessione.cd_conferenza
	 * @param cdConferenza  the value for sessione.cd_conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setCdConferenza(Integer cdConferenza) {
		this.cdConferenza = cdConferenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sessione.cd_report
	 * @return  the value of sessione.cd_report
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Integer getCdReport() {
		return cdReport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sessione.cd_report
	 * @param cdReport  the value for sessione.cd_report
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setCdReport(Integer cdReport) {
		this.cdReport = cdReport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sessione.ora_inizio
	 * @return  the value of sessione.ora_inizio
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Date getOraInizio() {
		return oraInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sessione.ora_inizio
	 * @param oraInizio  the value for sessione.ora_inizio
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setOraInizio(Date oraInizio) {
		this.oraInizio = oraInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sessione.ora_fine
	 * @return  the value of sessione.ora_fine
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Date getOraFine() {
		return oraFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sessione.ora_fine
	 * @param oraFine  the value for sessione.ora_fine
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setOraFine(Date oraFine) {
		this.oraFine = oraFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sessione.tipo_sessione
	 * @return  the value of sessione.tipo_sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public String getTipoSessione() {
		return tipoSessione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sessione.tipo_sessione
	 * @param tipoSessione  the value for sessione.tipo_sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setTipoSessione(String tipoSessione) {
		this.tipoSessione = tipoSessione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sessione.cd_persona_chair
	 * @return  the value of sessione.cd_persona_chair
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Integer getCdPersonaChair() {
		return cdPersonaChair;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sessione.cd_persona_chair
	 * @param cdPersonaChair  the value for sessione.cd_persona_chair
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setCdPersonaChair(Integer cdPersonaChair) {
		this.cdPersonaChair = cdPersonaChair;
	}
}