package com.gestioneconferenzews.DAO.model;

public class SessionePartecipanti {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sessione_partecipanti.cd_sessione_partecipanti
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	private Integer cdSessionePartecipanti;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sessione_partecipanti.cd_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	private Integer cdPersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sessione_partecipanti.tipo_partecipante
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	private String tipoPartecipante;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sessione_partecipanti.cd_sessione_partecipanti
	 * @return  the value of sessione_partecipanti.cd_sessione_partecipanti
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	public Integer getCdSessionePartecipanti() {
		return cdSessionePartecipanti;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sessione_partecipanti.cd_sessione_partecipanti
	 * @param cdSessionePartecipanti  the value for sessione_partecipanti.cd_sessione_partecipanti
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	public void setCdSessionePartecipanti(Integer cdSessionePartecipanti) {
		this.cdSessionePartecipanti = cdSessionePartecipanti;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sessione_partecipanti.cd_persona
	 * @return  the value of sessione_partecipanti.cd_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	public Integer getCdPersona() {
		return cdPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sessione_partecipanti.cd_persona
	 * @param cdPersona  the value for sessione_partecipanti.cd_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	public void setCdPersona(Integer cdPersona) {
		this.cdPersona = cdPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sessione_partecipanti.tipo_partecipante
	 * @return  the value of sessione_partecipanti.tipo_partecipante
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	public String getTipoPartecipante() {
		return tipoPartecipante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sessione_partecipanti.tipo_partecipante
	 * @param tipoPartecipante  the value for sessione_partecipanti.tipo_partecipante
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	public void setTipoPartecipante(String tipoPartecipante) {
		this.tipoPartecipante = tipoPartecipante;
	}
}