package com.gestioneconferenzews.DAO.model;

public class SessioneReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessione_report.cd_sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    private Integer cdSessioneReport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessione_report.cd_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    private Integer cdReport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessione_report.cd_sessione
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    private Integer cdSessione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessione_report.cd_sessione_report
     *
     * @return the value of sessione_report.cd_sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    public Integer getCdSessioneReport() {
        return cdSessioneReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessione_report.cd_sessione_report
     *
     * @param cdSessioneReport the value for sessione_report.cd_sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    public void setCdSessioneReport(Integer cdSessioneReport) {
        this.cdSessioneReport = cdSessioneReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessione_report.cd_report
     *
     * @return the value of sessione_report.cd_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    public Integer getCdReport() {
        return cdReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessione_report.cd_report
     *
     * @param cdReport the value for sessione_report.cd_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    public void setCdReport(Integer cdReport) {
        this.cdReport = cdReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessione_report.cd_sessione
     *
     * @return the value of sessione_report.cd_sessione
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    public Integer getCdSessione() {
        return cdSessione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessione_report.cd_sessione
     *
     * @param cdSessione the value for sessione_report.cd_sessione
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    public void setCdSessione(Integer cdSessione) {
        this.cdSessione = cdSessione;
    }
}