package com.gestioneconferenzews.DAO.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SessioneExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public SessioneExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCdSessioneIsNull() {
			addCriterion("cd_sessione is null");
			return (Criteria) this;
		}

		public Criteria andCdSessioneIsNotNull() {
			addCriterion("cd_sessione is not null");
			return (Criteria) this;
		}

		public Criteria andCdSessioneEqualTo(Integer value) {
			addCriterion("cd_sessione =", value, "cdSessione");
			return (Criteria) this;
		}

		public Criteria andCdSessioneNotEqualTo(Integer value) {
			addCriterion("cd_sessione <>", value, "cdSessione");
			return (Criteria) this;
		}

		public Criteria andCdSessioneGreaterThan(Integer value) {
			addCriterion("cd_sessione >", value, "cdSessione");
			return (Criteria) this;
		}

		public Criteria andCdSessioneGreaterThanOrEqualTo(Integer value) {
			addCriterion("cd_sessione >=", value, "cdSessione");
			return (Criteria) this;
		}

		public Criteria andCdSessioneLessThan(Integer value) {
			addCriterion("cd_sessione <", value, "cdSessione");
			return (Criteria) this;
		}

		public Criteria andCdSessioneLessThanOrEqualTo(Integer value) {
			addCriterion("cd_sessione <=", value, "cdSessione");
			return (Criteria) this;
		}

		public Criteria andCdSessioneIn(List<Integer> values) {
			addCriterion("cd_sessione in", values, "cdSessione");
			return (Criteria) this;
		}

		public Criteria andCdSessioneNotIn(List<Integer> values) {
			addCriterion("cd_sessione not in", values, "cdSessione");
			return (Criteria) this;
		}

		public Criteria andCdSessioneBetween(Integer value1, Integer value2) {
			addCriterion("cd_sessione between", value1, value2, "cdSessione");
			return (Criteria) this;
		}

		public Criteria andCdSessioneNotBetween(Integer value1, Integer value2) {
			addCriterion("cd_sessione not between", value1, value2,
					"cdSessione");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaIsNull() {
			addCriterion("cd_conferenza is null");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaIsNotNull() {
			addCriterion("cd_conferenza is not null");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaEqualTo(Integer value) {
			addCriterion("cd_conferenza =", value, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaNotEqualTo(Integer value) {
			addCriterion("cd_conferenza <>", value, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaGreaterThan(Integer value) {
			addCriterion("cd_conferenza >", value, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaGreaterThanOrEqualTo(Integer value) {
			addCriterion("cd_conferenza >=", value, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaLessThan(Integer value) {
			addCriterion("cd_conferenza <", value, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaLessThanOrEqualTo(Integer value) {
			addCriterion("cd_conferenza <=", value, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaIn(List<Integer> values) {
			addCriterion("cd_conferenza in", values, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaNotIn(List<Integer> values) {
			addCriterion("cd_conferenza not in", values, "cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaBetween(Integer value1, Integer value2) {
			addCriterion("cd_conferenza between", value1, value2,
					"cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdConferenzaNotBetween(Integer value1, Integer value2) {
			addCriterion("cd_conferenza not between", value1, value2,
					"cdConferenza");
			return (Criteria) this;
		}

		public Criteria andCdReportIsNull() {
			addCriterion("cd_report is null");
			return (Criteria) this;
		}

		public Criteria andCdReportIsNotNull() {
			addCriterion("cd_report is not null");
			return (Criteria) this;
		}

		public Criteria andCdReportEqualTo(Integer value) {
			addCriterion("cd_report =", value, "cdReport");
			return (Criteria) this;
		}

		public Criteria andCdReportNotEqualTo(Integer value) {
			addCriterion("cd_report <>", value, "cdReport");
			return (Criteria) this;
		}

		public Criteria andCdReportGreaterThan(Integer value) {
			addCriterion("cd_report >", value, "cdReport");
			return (Criteria) this;
		}

		public Criteria andCdReportGreaterThanOrEqualTo(Integer value) {
			addCriterion("cd_report >=", value, "cdReport");
			return (Criteria) this;
		}

		public Criteria andCdReportLessThan(Integer value) {
			addCriterion("cd_report <", value, "cdReport");
			return (Criteria) this;
		}

		public Criteria andCdReportLessThanOrEqualTo(Integer value) {
			addCriterion("cd_report <=", value, "cdReport");
			return (Criteria) this;
		}

		public Criteria andCdReportIn(List<Integer> values) {
			addCriterion("cd_report in", values, "cdReport");
			return (Criteria) this;
		}

		public Criteria andCdReportNotIn(List<Integer> values) {
			addCriterion("cd_report not in", values, "cdReport");
			return (Criteria) this;
		}

		public Criteria andCdReportBetween(Integer value1, Integer value2) {
			addCriterion("cd_report between", value1, value2, "cdReport");
			return (Criteria) this;
		}

		public Criteria andCdReportNotBetween(Integer value1, Integer value2) {
			addCriterion("cd_report not between", value1, value2, "cdReport");
			return (Criteria) this;
		}

		public Criteria andOraInizioIsNull() {
			addCriterion("ora_inizio is null");
			return (Criteria) this;
		}

		public Criteria andOraInizioIsNotNull() {
			addCriterion("ora_inizio is not null");
			return (Criteria) this;
		}

		public Criteria andOraInizioEqualTo(Date value) {
			addCriterion("ora_inizio =", value, "oraInizio");
			return (Criteria) this;
		}

		public Criteria andOraInizioNotEqualTo(Date value) {
			addCriterion("ora_inizio <>", value, "oraInizio");
			return (Criteria) this;
		}

		public Criteria andOraInizioGreaterThan(Date value) {
			addCriterion("ora_inizio >", value, "oraInizio");
			return (Criteria) this;
		}

		public Criteria andOraInizioGreaterThanOrEqualTo(Date value) {
			addCriterion("ora_inizio >=", value, "oraInizio");
			return (Criteria) this;
		}

		public Criteria andOraInizioLessThan(Date value) {
			addCriterion("ora_inizio <", value, "oraInizio");
			return (Criteria) this;
		}

		public Criteria andOraInizioLessThanOrEqualTo(Date value) {
			addCriterion("ora_inizio <=", value, "oraInizio");
			return (Criteria) this;
		}

		public Criteria andOraInizioIn(List<Date> values) {
			addCriterion("ora_inizio in", values, "oraInizio");
			return (Criteria) this;
		}

		public Criteria andOraInizioNotIn(List<Date> values) {
			addCriterion("ora_inizio not in", values, "oraInizio");
			return (Criteria) this;
		}

		public Criteria andOraInizioBetween(Date value1, Date value2) {
			addCriterion("ora_inizio between", value1, value2, "oraInizio");
			return (Criteria) this;
		}

		public Criteria andOraInizioNotBetween(Date value1, Date value2) {
			addCriterion("ora_inizio not between", value1, value2, "oraInizio");
			return (Criteria) this;
		}

		public Criteria andOraFineIsNull() {
			addCriterion("ora_fine is null");
			return (Criteria) this;
		}

		public Criteria andOraFineIsNotNull() {
			addCriterion("ora_fine is not null");
			return (Criteria) this;
		}

		public Criteria andOraFineEqualTo(Date value) {
			addCriterion("ora_fine =", value, "oraFine");
			return (Criteria) this;
		}

		public Criteria andOraFineNotEqualTo(Date value) {
			addCriterion("ora_fine <>", value, "oraFine");
			return (Criteria) this;
		}

		public Criteria andOraFineGreaterThan(Date value) {
			addCriterion("ora_fine >", value, "oraFine");
			return (Criteria) this;
		}

		public Criteria andOraFineGreaterThanOrEqualTo(Date value) {
			addCriterion("ora_fine >=", value, "oraFine");
			return (Criteria) this;
		}

		public Criteria andOraFineLessThan(Date value) {
			addCriterion("ora_fine <", value, "oraFine");
			return (Criteria) this;
		}

		public Criteria andOraFineLessThanOrEqualTo(Date value) {
			addCriterion("ora_fine <=", value, "oraFine");
			return (Criteria) this;
		}

		public Criteria andOraFineIn(List<Date> values) {
			addCriterion("ora_fine in", values, "oraFine");
			return (Criteria) this;
		}

		public Criteria andOraFineNotIn(List<Date> values) {
			addCriterion("ora_fine not in", values, "oraFine");
			return (Criteria) this;
		}

		public Criteria andOraFineBetween(Date value1, Date value2) {
			addCriterion("ora_fine between", value1, value2, "oraFine");
			return (Criteria) this;
		}

		public Criteria andOraFineNotBetween(Date value1, Date value2) {
			addCriterion("ora_fine not between", value1, value2, "oraFine");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneIsNull() {
			addCriterion("tipo_sessione is null");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneIsNotNull() {
			addCriterion("tipo_sessione is not null");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneEqualTo(String value) {
			addCriterion("tipo_sessione =", value, "tipoSessione");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneNotEqualTo(String value) {
			addCriterion("tipo_sessione <>", value, "tipoSessione");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneGreaterThan(String value) {
			addCriterion("tipo_sessione >", value, "tipoSessione");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneGreaterThanOrEqualTo(String value) {
			addCriterion("tipo_sessione >=", value, "tipoSessione");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneLessThan(String value) {
			addCriterion("tipo_sessione <", value, "tipoSessione");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneLessThanOrEqualTo(String value) {
			addCriterion("tipo_sessione <=", value, "tipoSessione");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneLike(String value) {
			addCriterion("tipo_sessione like", value, "tipoSessione");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneNotLike(String value) {
			addCriterion("tipo_sessione not like", value, "tipoSessione");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneIn(List<String> values) {
			addCriterion("tipo_sessione in", values, "tipoSessione");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneNotIn(List<String> values) {
			addCriterion("tipo_sessione not in", values, "tipoSessione");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneBetween(String value1, String value2) {
			addCriterion("tipo_sessione between", value1, value2,
					"tipoSessione");
			return (Criteria) this;
		}

		public Criteria andTipoSessioneNotBetween(String value1, String value2) {
			addCriterion("tipo_sessione not between", value1, value2,
					"tipoSessione");
			return (Criteria) this;
		}

		public Criteria andCdPersonaChairIsNull() {
			addCriterion("cd_persona_chair is null");
			return (Criteria) this;
		}

		public Criteria andCdPersonaChairIsNotNull() {
			addCriterion("cd_persona_chair is not null");
			return (Criteria) this;
		}

		public Criteria andCdPersonaChairEqualTo(Integer value) {
			addCriterion("cd_persona_chair =", value, "cdPersonaChair");
			return (Criteria) this;
		}

		public Criteria andCdPersonaChairNotEqualTo(Integer value) {
			addCriterion("cd_persona_chair <>", value, "cdPersonaChair");
			return (Criteria) this;
		}

		public Criteria andCdPersonaChairGreaterThan(Integer value) {
			addCriterion("cd_persona_chair >", value, "cdPersonaChair");
			return (Criteria) this;
		}

		public Criteria andCdPersonaChairGreaterThanOrEqualTo(Integer value) {
			addCriterion("cd_persona_chair >=", value, "cdPersonaChair");
			return (Criteria) this;
		}

		public Criteria andCdPersonaChairLessThan(Integer value) {
			addCriterion("cd_persona_chair <", value, "cdPersonaChair");
			return (Criteria) this;
		}

		public Criteria andCdPersonaChairLessThanOrEqualTo(Integer value) {
			addCriterion("cd_persona_chair <=", value, "cdPersonaChair");
			return (Criteria) this;
		}

		public Criteria andCdPersonaChairIn(List<Integer> values) {
			addCriterion("cd_persona_chair in", values, "cdPersonaChair");
			return (Criteria) this;
		}

		public Criteria andCdPersonaChairNotIn(List<Integer> values) {
			addCriterion("cd_persona_chair not in", values, "cdPersonaChair");
			return (Criteria) this;
		}

		public Criteria andCdPersonaChairBetween(Integer value1, Integer value2) {
			addCriterion("cd_persona_chair between", value1, value2,
					"cdPersonaChair");
			return (Criteria) this;
		}

		public Criteria andCdPersonaChairNotBetween(Integer value1,
				Integer value2) {
			addCriterion("cd_persona_chair not between", value1, value2,
					"cdPersonaChair");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sessione
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sessione
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 02 21:29:16 CEST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}