package com.gestioneconferenzews.DAO.model;

public class StrutturaConvenzionata {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura_convenzionata.cd_struttura_convenzionata
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	private Integer cdStrutturaConvenzionata;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura_convenzionata.tipo_struttura
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	private Integer tipoStruttura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura_convenzionata.indirizzo
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	private String indirizzo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura_convenzionata.comune
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	private String comune;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura_convenzionata.descrizione
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	private String descrizione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura_convenzionata.url_servizio
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	private String urlServizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura_convenzionata.nome
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	private String nome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura_convenzionata.tipo_servizio
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	private String tipoServizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura_convenzionata.codice_convenzione
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	private String codiceConvenzione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura_convenzionata.cd_struttura_convenzionata
	 * @return  the value of struttura_convenzionata.cd_struttura_convenzionata
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public Integer getCdStrutturaConvenzionata() {
		return cdStrutturaConvenzionata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura_convenzionata.cd_struttura_convenzionata
	 * @param cdStrutturaConvenzionata  the value for struttura_convenzionata.cd_struttura_convenzionata
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public void setCdStrutturaConvenzionata(Integer cdStrutturaConvenzionata) {
		this.cdStrutturaConvenzionata = cdStrutturaConvenzionata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura_convenzionata.tipo_struttura
	 * @return  the value of struttura_convenzionata.tipo_struttura
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public Integer getTipoStruttura() {
		return tipoStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura_convenzionata.tipo_struttura
	 * @param tipoStruttura  the value for struttura_convenzionata.tipo_struttura
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public void setTipoStruttura(Integer tipoStruttura) {
		this.tipoStruttura = tipoStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura_convenzionata.indirizzo
	 * @return  the value of struttura_convenzionata.indirizzo
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public String getIndirizzo() {
		return indirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura_convenzionata.indirizzo
	 * @param indirizzo  the value for struttura_convenzionata.indirizzo
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura_convenzionata.comune
	 * @return  the value of struttura_convenzionata.comune
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public String getComune() {
		return comune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura_convenzionata.comune
	 * @param comune  the value for struttura_convenzionata.comune
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public void setComune(String comune) {
		this.comune = comune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura_convenzionata.descrizione
	 * @return  the value of struttura_convenzionata.descrizione
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public String getDescrizione() {
		return descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura_convenzionata.descrizione
	 * @param descrizione  the value for struttura_convenzionata.descrizione
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura_convenzionata.url_servizio
	 * @return  the value of struttura_convenzionata.url_servizio
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public String getUrlServizio() {
		return urlServizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura_convenzionata.url_servizio
	 * @param urlServizio  the value for struttura_convenzionata.url_servizio
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public void setUrlServizio(String urlServizio) {
		this.urlServizio = urlServizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura_convenzionata.nome
	 * @return  the value of struttura_convenzionata.nome
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura_convenzionata.nome
	 * @param nome  the value for struttura_convenzionata.nome
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura_convenzionata.tipo_servizio
	 * @return  the value of struttura_convenzionata.tipo_servizio
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public String getTipoServizio() {
		return tipoServizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura_convenzionata.tipo_servizio
	 * @param tipoServizio  the value for struttura_convenzionata.tipo_servizio
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public void setTipoServizio(String tipoServizio) {
		this.tipoServizio = tipoServizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura_convenzionata.codice_convenzione
	 * @return  the value of struttura_convenzionata.codice_convenzione
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public String getCodiceConvenzione() {
		return codiceConvenzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura_convenzionata.codice_convenzione
	 * @param codiceConvenzione  the value for struttura_convenzionata.codice_convenzione
	 * @mbggenerated  Wed Mar 26 22:33:54 CET 2014
	 */
	public void setCodiceConvenzione(String codiceConvenzione) {
		this.codiceConvenzione = codiceConvenzione;
	}
}