package com.gestioneconferenzews.DAO.model;

public class TipoReport {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tipo_report.cd_tipo_Report
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private Integer cdTipoReport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tipo_report.tipo_report
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	private String tipoReport;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tipo_report.cd_tipo_Report
	 * @return  the value of tipo_report.cd_tipo_Report
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public Integer getCdTipoReport() {
		return cdTipoReport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tipo_report.cd_tipo_Report
	 * @param cdTipoReport  the value for tipo_report.cd_tipo_Report
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setCdTipoReport(Integer cdTipoReport) {
		this.cdTipoReport = cdTipoReport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tipo_report.tipo_report
	 * @return  the value of tipo_report.tipo_report
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public String getTipoReport() {
		return tipoReport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tipo_report.tipo_report
	 * @param tipoReport  the value for tipo_report.tipo_report
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	public void setTipoReport(String tipoReport) {
		this.tipoReport = tipoReport;
	}
}