package com.gestioneconferenzews.DAO.mapper;

import com.gestioneconferenzews.DAO.model.Budget;
import com.gestioneconferenzews.DAO.model.BudgetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BudgetMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table budget
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int countByExample(BudgetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table budget
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int deleteByExample(BudgetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table budget
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int deleteByPrimaryKey(Integer cdBudget);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table budget
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int insert(Budget record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table budget
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int insertSelective(Budget record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table budget
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	List<Budget> selectByExample(BudgetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table budget
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	Budget selectByPrimaryKey(Integer cdBudget);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table budget
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int updateByExampleSelective(@Param("record") Budget record,
			@Param("example") BudgetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table budget
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int updateByExample(@Param("record") Budget record,
			@Param("example") BudgetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table budget
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int updateByPrimaryKeySelective(Budget record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table budget
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int updateByPrimaryKey(Budget record);
}