package com.gestioneconferenzews.DAO.mapper;

import com.gestioneconferenzews.DAO.model.ComitatoPersona;
import com.gestioneconferenzews.DAO.model.ComitatoPersonaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComitatoPersonaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comitato_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int countByExample(ComitatoPersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comitato_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int deleteByExample(ComitatoPersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comitato_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int deleteByPrimaryKey(Integer cdComitatoPersona);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comitato_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int insert(ComitatoPersona record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comitato_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int insertSelective(ComitatoPersona record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comitato_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	List<ComitatoPersona> selectByExample(ComitatoPersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comitato_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	ComitatoPersona selectByPrimaryKey(Integer cdComitatoPersona);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comitato_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int updateByExampleSelective(@Param("record") ComitatoPersona record,
			@Param("example") ComitatoPersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comitato_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int updateByExample(@Param("record") ComitatoPersona record,
			@Param("example") ComitatoPersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comitato_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int updateByPrimaryKeySelective(ComitatoPersona record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comitato_persona
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int updateByPrimaryKey(ComitatoPersona record);
}