package com.gestioneconferenzews.DAO.mapper;

import com.gestioneconferenzews.DAO.model.Conferenza;
import com.gestioneconferenzews.DAO.model.ConferenzaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConferenzaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int countByExample(ConferenzaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int deleteByExample(ConferenzaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int deleteByPrimaryKey(Integer cdConferenza);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int insert(Conferenza record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int insertSelective(Conferenza record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	List<Conferenza> selectByExample(ConferenzaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	Conferenza selectByPrimaryKey(Integer cdConferenza);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int updateByExampleSelective(@Param("record") Conferenza record,
			@Param("example") ConferenzaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int updateByExample(@Param("record") Conferenza record,
			@Param("example") ConferenzaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int updateByPrimaryKeySelective(Conferenza record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table conferenza
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int updateByPrimaryKey(Conferenza record);

	List<Conferenza> selectConferenzeTutte();
	
}