package com.gestioneconferenzews.DAO.mapper;

import com.gestioneconferenzews.DAO.model.ElencoStatistiche;
import com.gestioneconferenzews.DAO.model.ElencoStatisticheExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ElencoStatisticheMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table elenco_statistiche
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int countByExample(ElencoStatisticheExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table elenco_statistiche
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int deleteByExample(ElencoStatisticheExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table elenco_statistiche
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int deleteByPrimaryKey(Integer cdElencoStatistiche);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table elenco_statistiche
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int insert(ElencoStatistiche record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table elenco_statistiche
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int insertSelective(ElencoStatistiche record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table elenco_statistiche
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	List<ElencoStatistiche> selectByExample(ElencoStatisticheExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table elenco_statistiche
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	ElencoStatistiche selectByPrimaryKey(Integer cdElencoStatistiche);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table elenco_statistiche
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int updateByExampleSelective(@Param("record") ElencoStatistiche record,
			@Param("example") ElencoStatisticheExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table elenco_statistiche
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int updateByExample(@Param("record") ElencoStatistiche record,
			@Param("example") ElencoStatisticheExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table elenco_statistiche
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int updateByPrimaryKeySelective(ElencoStatistiche record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table elenco_statistiche
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int updateByPrimaryKey(ElencoStatistiche record);

	List<ElencoStatistiche> selectQueryTutte();
}