package com.gestioneconferenzews.DAO.mapper;

import com.gestioneconferenzews.DAO.model.Investimento;
import com.gestioneconferenzews.DAO.model.InvestimentoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvestimentoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investimento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int countByExample(InvestimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investimento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int deleteByExample(InvestimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investimento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int deleteByPrimaryKey(Integer cdInvestimento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investimento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int insert(Investimento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investimento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int insertSelective(Investimento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investimento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	List<Investimento> selectByExample(InvestimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investimento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	Investimento selectByPrimaryKey(Integer cdInvestimento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investimento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int updateByExampleSelective(@Param("record") Investimento record,
			@Param("example") InvestimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investimento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int updateByExample(@Param("record") Investimento record,
			@Param("example") InvestimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investimento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int updateByPrimaryKeySelective(Investimento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investimento
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int updateByPrimaryKey(Investimento record);
}