package com.gestioneconferenzews.DAO.mapper;

import com.gestioneconferenzews.DAO.model.Pagamento;
import com.gestioneconferenzews.DAO.model.PagamentoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PagamentoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int countByExample(PagamentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int deleteByExample(PagamentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int deleteByPrimaryKey(Integer cdPagamento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int insert(Pagamento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int insertSelective(Pagamento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	List<Pagamento> selectByExample(PagamentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	Pagamento selectByPrimaryKey(Integer cdPagamento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int updateByExampleSelective(@Param("record") Pagamento record,
			@Param("example") PagamentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int updateByExample(@Param("record") Pagamento record,
			@Param("example") PagamentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int updateByPrimaryKeySelective(Pagamento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagamento
	 * @mbggenerated  Tue Apr 15 21:14:28 CEST 2014
	 */
	int updateByPrimaryKey(Pagamento record);
}