package com.gestioneconferenzews.DAO.mapper;

import com.gestioneconferenzews.DAO.model.Persona;
import com.gestioneconferenzews.DAO.model.PersonaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persona
	 * @mbggenerated  Sun Mar 23 21:34:13 CET 2014
	 */
	int countByExample(PersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persona
	 * @mbggenerated  Sun Mar 23 21:34:13 CET 2014
	 */
	int deleteByExample(PersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persona
	 * @mbggenerated  Sun Mar 23 21:34:13 CET 2014
	 */
	int deleteByPrimaryKey(Integer cdPersona);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persona
	 * @mbggenerated  Sun Mar 23 21:34:13 CET 2014
	 */
	int insert(Persona record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persona
	 * @mbggenerated  Sun Mar 23 21:34:13 CET 2014
	 */
	int insertSelective(Persona record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persona
	 * @mbggenerated  Sun Mar 23 21:34:13 CET 2014
	 */
	List<Persona> selectByExample(PersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persona
	 * @mbggenerated  Sun Mar 23 21:34:13 CET 2014
	 */
	Persona selectByPrimaryKey(Integer cdPersona);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persona
	 * @mbggenerated  Sun Mar 23 21:34:13 CET 2014
	 */
	int updateByExampleSelective(@Param("record") Persona record,
			@Param("example") PersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persona
	 * @mbggenerated  Sun Mar 23 21:34:13 CET 2014
	 */
	int updateByExample(@Param("record") Persona record,
			@Param("example") PersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persona
	 * @mbggenerated  Sun Mar 23 21:34:13 CET 2014
	 */
	int updateByPrimaryKeySelective(Persona record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table persona
	 * @mbggenerated  Sun Mar 23 21:34:13 CET 2014
	 */
	int updateByPrimaryKey(Persona record);
	
	List<Persona> selectPersonaTutte();
}