package com.gestioneconferenzews.DAO.mapper;

import com.gestioneconferenzews.DAO.model.Regione;
import com.gestioneconferenzews.DAO.model.RegioneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegioneMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regione
	 * @mbggenerated  Wed Mar 12 22:35:50 CET 2014
	 */
	int countByExample(RegioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regione
	 * @mbggenerated  Wed Mar 12 22:35:50 CET 2014
	 */
	int deleteByExample(RegioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regione
	 * @mbggenerated  Wed Mar 12 22:35:50 CET 2014
	 */
	int deleteByPrimaryKey(String codiceIstatRegione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regione
	 * @mbggenerated  Wed Mar 12 22:35:50 CET 2014
	 */
	int insert(Regione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regione
	 * @mbggenerated  Wed Mar 12 22:35:50 CET 2014
	 */
	int insertSelective(Regione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regione
	 * @mbggenerated  Wed Mar 12 22:35:50 CET 2014
	 */
	List<Regione> selectByExample(RegioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regione
	 * @mbggenerated  Wed Mar 12 22:35:50 CET 2014
	 */
	Regione selectByPrimaryKey(String codiceIstatRegione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regione
	 * @mbggenerated  Wed Mar 12 22:35:50 CET 2014
	 */
	int updateByExampleSelective(@Param("record") Regione record,
			@Param("example") RegioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regione
	 * @mbggenerated  Wed Mar 12 22:35:50 CET 2014
	 */
	int updateByExample(@Param("record") Regione record,
			@Param("example") RegioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regione
	 * @mbggenerated  Wed Mar 12 22:35:50 CET 2014
	 */
	int updateByPrimaryKeySelective(Regione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regione
	 * @mbggenerated  Wed Mar 12 22:35:50 CET 2014
	 */
	int updateByPrimaryKey(Regione record);
}