package com.gestioneconferenzews.DAO.mapper;

import com.gestioneconferenzews.DAO.model.ReportAutore;
import com.gestioneconferenzews.DAO.model.ReportAutoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportAutoreMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report_autore
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int countByExample(ReportAutoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report_autore
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int deleteByExample(ReportAutoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report_autore
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int deleteByPrimaryKey(Integer cdReportAutore);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report_autore
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int insert(ReportAutore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report_autore
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int insertSelective(ReportAutore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report_autore
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	List<ReportAutore> selectByExample(ReportAutoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report_autore
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	ReportAutore selectByPrimaryKey(Integer cdReportAutore);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report_autore
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int updateByExampleSelective(@Param("record") ReportAutore record,
			@Param("example") ReportAutoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report_autore
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int updateByExample(@Param("record") ReportAutore record,
			@Param("example") ReportAutoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report_autore
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int updateByPrimaryKeySelective(ReportAutore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report_autore
	 * @mbggenerated  Fri Apr 25 11:55:32 CEST 2014
	 */
	int updateByPrimaryKey(ReportAutore record);
}