package com.gestioneconferenzews.DAO.mapper;

import com.gestioneconferenzews.DAO.model.RuoloPersonaExample;
import com.gestioneconferenzews.DAO.model.RuoloPersonaKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RuoloPersonaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ruolo_persona
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int countByExample(RuoloPersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ruolo_persona
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int deleteByExample(RuoloPersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ruolo_persona
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int deleteByPrimaryKey(RuoloPersonaKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ruolo_persona
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int insert(RuoloPersonaKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ruolo_persona
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int insertSelective(RuoloPersonaKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ruolo_persona
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	List<RuoloPersonaKey> selectByExample(RuoloPersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ruolo_persona
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int updateByExampleSelective(@Param("record") RuoloPersonaKey record,
			@Param("example") RuoloPersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ruolo_persona
	 * @mbggenerated  Thu Apr 24 10:04:47 CEST 2014
	 */
	int updateByExample(@Param("record") RuoloPersonaKey record,
			@Param("example") RuoloPersonaExample example);
}