package com.gestioneconferenzews.DAO.mapper;

import com.gestioneconferenzews.DAO.model.SessioneReport;
import com.gestioneconferenzews.DAO.model.SessioneReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SessioneReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    int countByExample(SessioneReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    int deleteByExample(SessioneReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    int deleteByPrimaryKey(Integer cdSessioneReport);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    int insert(SessioneReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    int insertSelective(SessioneReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    List<SessioneReport> selectByExample(SessioneReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    SessioneReport selectByPrimaryKey(Integer cdSessioneReport);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    int updateByExampleSelective(@Param("record") SessioneReport record, @Param("example") SessioneReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    int updateByExample(@Param("record") SessioneReport record, @Param("example") SessioneReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    int updateByPrimaryKeySelective(SessioneReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessione_report
     *
     * @mbggenerated Fri Apr 25 11:55:33 CEST 2014
     */
    int updateByPrimaryKey(SessioneReport record);
}