package com.gestioneconferenzews.DAO.mapper;

import com.gestioneconferenzews.DAO.model.Sponsor;
import com.gestioneconferenzews.DAO.model.SponsorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SponsorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsor
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int countByExample(SponsorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsor
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int deleteByExample(SponsorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsor
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int deleteByPrimaryKey(Integer cdSponsor);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsor
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int insert(Sponsor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsor
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int insertSelective(Sponsor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsor
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	List<Sponsor> selectByExample(SponsorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsor
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	Sponsor selectByPrimaryKey(Integer cdSponsor);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsor
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int updateByExampleSelective(@Param("record") Sponsor record,
			@Param("example") SponsorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsor
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int updateByExample(@Param("record") Sponsor record,
			@Param("example") SponsorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsor
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int updateByPrimaryKeySelective(Sponsor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sponsor
	 * @mbggenerated  Wed Apr 09 15:54:22 CEST 2014
	 */
	int updateByPrimaryKey(Sponsor record);
}