package com.gestioneconferenzews.DAO.mapper;

import com.gestioneconferenzews.DAO.model.TipoPartecipante;
import com.gestioneconferenzews.DAO.model.TipoPartecipanteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipoPartecipanteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:33 CEST 2014
	 */
	int countByExample(TipoPartecipanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:33 CEST 2014
	 */
	int deleteByExample(TipoPartecipanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:33 CEST 2014
	 */
	int deleteByPrimaryKey(Integer cdTipoPartecipante);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:33 CEST 2014
	 */
	int insert(TipoPartecipante record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:33 CEST 2014
	 */
	int insertSelective(TipoPartecipante record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:33 CEST 2014
	 */
	List<TipoPartecipante> selectByExample(TipoPartecipanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:33 CEST 2014
	 */
	TipoPartecipante selectByPrimaryKey(Integer cdTipoPartecipante);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:33 CEST 2014
	 */
	int updateByExampleSelective(@Param("record") TipoPartecipante record,
			@Param("example") TipoPartecipanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:33 CEST 2014
	 */
	int updateByExample(@Param("record") TipoPartecipante record,
			@Param("example") TipoPartecipanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:33 CEST 2014
	 */
	int updateByPrimaryKeySelective(TipoPartecipante record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_partecipante
	 * @mbggenerated  Fri Apr 25 11:55:33 CEST 2014
	 */
	int updateByPrimaryKey(TipoPartecipante record);
}